### PR TITLE
Enable Swift 6 mode when available, sync `QueryEngine` sources

### PR DESCRIPTION
**Pull request by MaxDesiatov**
As SwiftPM is more actively developed, let's consider it to be the source of truth and vendor `QueryEngine` back into `swift-sdk-generator` together with more fresh `AsyncFileSystem` code, storing all those files in `Source/Helpers/Vendor` subdirectory.

All this allows us to fix concurrency errors that prevent it from building in Swift 6 mode.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
Let me check 5.8 compatibility before merging

**Comment by kateinoigakukun** [comment]
@MaxDesiatov We need this change against AsyncFileSystem to keep 5.8 compatibility. https://github.com/swiftlang/swift-package-manager/pull/7928
Could you update the vendored files after the PR is merged?

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@kateinoigakukun done, ready for review

**Review by kateinoigakukun — APPROVED** [review]

**Pull request merged**
